apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: sfogo-cluster
# Server are Control Planes
servers: 1
# Agents are Nodes
agents: 1
kubeAPI:
  host: master.127.0.0.1.nip.io
  hostIP: "127.0.0.1"
  hostPort: "6445"
image: rancher/k3s:v1.28.8-k3s1
ports:
  - port: 8199:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1.nip.io
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
